CREATE DATABASE CougNotes;
USE CougNotes;

CREATE TABLE students (
	uid SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	firstName VARCHAR(200) NOT NULL,
	lastName  VARCHAR(200) NOT NULL,
	profilePic TEXT,
	studentID SMALLINT UNSIGNED NOT NULL
	) ENGINE = InnoDB;

CREATE TABLE Notes (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	content text, imageURLs text,
	students_uid SMALLINT UNSIGNED NOT NULL,
	CONSTRAINT `fk_studentUID`  FOREIGN KEY (students_uid) REFERENCES students (uid)
		ON DELETE CASCADE
		ON UPDATE RESTRICT
	) ENGINE = InnoDB;

CREATE TABLE classCodes (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
);


CREATE TABLE classes (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	className VARCHAR(100) NOT NULL,
	section VARCHAR(10) NOT NULL,
	classCodes_id SMALLINT UNSIGNED NOT NULL,
	CONSTRAINT `fk_classCode` FOREIGN KEY (classCodes_id) REFERENCES classCodes (id)
		ON DELETE CASCADE
		ON UPDATE RESTRICT
	) Engine = InnoDB;

SHOW tables;
