[package]
name = "CougNotes"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmedge_quickjs = "0.2.0"
sqlx = { version = "0.5", features = [ "runtime-async-std-native-tls", "mysql" ] }